# Generated by Django 4.1.2 on 2022-10-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicity_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='artist_id',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='musicity_db.artist'),
            preserve_default=False,
        ),
    ]
