# Generated by Django 4.1.2 on 2022-10-30 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(choices=[('r', 'rock'), ('j', 'jazz'), ('cl', 'classical'), ('p', 'pop'), ('rb', 'r&b'), ('c', 'country'), ('hh', 'hip-hop'), ('e', 'dance/electronic'), ('l', 'latin')], max_length=2)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicity_db.artist')),
            ],
        ),
    ]
