# Generated by Django 4.1.3 on 2022-12-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicity_db', '0013_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('r', 'rock'), ('j', 'jazz'), ('cl', 'classical'), ('p', 'pop'), ('rb', 'r&b'), ('c', 'country'), ('hh', 'hip-hop'), ('e', 'dance/electronic'), ('l', 'latin')], max_length=2)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicity_db.artist')),
            ],
        ),
    ]
