# Generated by Django 4.1.2 on 2022-12-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicity_db', '0017_artist_label_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('r', 'rock'), ('j', 'jazz'), ('cl', 'classical'), ('p', 'pop'), ('rb', 'r&b'), ('c', 'country'), ('hh', 'hip-hop'), ('e', 'dance/electronic'), ('l', 'latin'), ('e', 'experimental'), ('na', 'N/A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('r', 'rock'), ('j', 'jazz'), ('cl', 'classical'), ('p', 'pop'), ('rb', 'r&b'), ('c', 'country'), ('hh', 'hip-hop'), ('e', 'dance/electronic'), ('l', 'latin'), ('e', 'experimental'), ('na', 'N/A')], max_length=2),
        ),
    ]
