# Generated by Django 4.1.2 on 2022-12-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicity_db', '0018_alter_album_genre_alter_track_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicity_db.album'),
        ),
    ]
