# Generated by Django 4.1.2 on 2022-12-05 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicity_db', '0019_alter_track_album_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.date(2022, 12, 5)),
            preserve_default=False,
        ),
    ]
