# Generated by Django 4.1.2 on 2022-12-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicity_db', '0020_album_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streams', models.PositiveIntegerField(default=10)),
                ('track_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicity_db.track')),
            ],
        ),
    ]
